#!/bin/bash

# Makes use of the dokku-build-hook plugin
# https://github.com/fteychene/dokku-build-hook

echo "Download legal pages"

curl \
  -H "Accept: application/vnd.github.raw" \
  -H "Authorization: Bearer ${PAT}"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/dicebear/legal/contents/site-notice.md \
  > docs/legal/site-notice.md

curl \
  -H "Accept: application/vnd.github.raw" \
  -H "Authorization: Bearer ${PAT}"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/dicebear/legal/contents/privacy-policy.md \
  > docs/legal/privacy-policy.md
