name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Download legal pages
        env:
          PAT: ${{ secrets.PAT }}
        run: ./scripts/download-legal-pages.sh

      - name: Build with VitePress
        run: |
          bun run build

      - name: Upload files to ftp server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          protocol: ftps
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./docs/.vitepress/dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}

      - name: Purge CDN Cache
        run: |
          curl --request POST \
            --url https://api.bunny.net/pullzone/${{ vars.CDN_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_KEY }}'
